// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    import.meta.env.SUPABASE_URL ||
    process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // Helpful diagnostics for local dev
    const keys = typeof import.meta !== "undefined" ? Object.keys(import.meta.env ?? {}) : [];
    const hinted = keys.filter(
      (k) => k.includes("SUPABASE") || k === "MODE" || k === "BASE_URL" || k === "DEV",
    );
    throw new Error(
      [
        "Missing Supabase environment variables.",
        "Expected VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (recommended) or SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (SSR).",
        "If running locally, ensure your `.env` file is in the Vite project root (the folder containing `vite.config.ts`).",
        hinted.length ? `Visible import.meta.env keys: ${hinted.join(", ")}` : "",
      ]
        .filter(Boolean)
        .join("\n"),
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

